twist_mux:
  ros__parameters:
    use_stamped: true
    topics:
      navigation:
        topic   : /nav_cmd_vel
        timeout : 0.5
        priority: 10
      joy_cmd:
        topic   : /joy_cmd
        timeout : 0.5
        priority: 100
      keyboard:
        topic   : /keyboard_cmd_vel
        timeout : 0.5
        priority: 90
