services:
  lawan_node:
    build:
      context: .
      dockerfile: Dockerfile
    image: lawan_node:latest

    volumes:
      - ../:/car_ws/src

    working_dir: /car_ws

    # command:
    #   - /bin/bash
    #   - -c
    #   - |
    #     source /ros_entrypoint.sh
    #     source install/setup.bash
    #     ros2 run demo_nodes_cpp talker
    environment:
      - ROS_DOMAIN_ID
    
    restart: always
    network_mode: host
    ipc: host
    pid: host
    command: su - ubuntu --whitelist-environment=\"ROS_DOMAIN_ID\" /run.sh