//! The UTM projection, ported from GeographicLib 2.3 (`TransverseMercator.cpp`,
//! `UTMUPS.cpp`, `Math.cpp`) — the same library and version that
//! `navsat_transform` links against, via `navsat_conversions.hpp`.
//!
//! Only the UTM branch is ported; the polar UPS branch returns an error (this
//! robot mows lawns, not ice shelves). See the crate README.

// The shapes below are GeographicLib's, kept as-is so the port reads against
// the C++: `!(x >= y)` is its NaN-safe guard, and the MGRS tile arithmetic is
// spelled out the way UTMUPS.cpp spells it.
#![allow(clippy::neg_cmp_op_on_partial_ord)]
#![allow(clippy::identity_op)]
#![allow(clippy::manual_range_contains)]

const MAXPOW: usize = 6;
const QD: f64 = 90.0;
const HD: f64 = 180.0;
const TD: f64 = 360.0;
const DEGREE: f64 = std::f64::consts::PI / 180.0;

const WGS84_A: f64 = 6378137.0;
const UTM_K0: f64 = 0.9996;
const TILE: f64 = 100_000.0;

fn wgs84_f() -> f64 {
    // Constants::WGS84_f(): 1 / (298257223563 / 1e9).
    1.0 / (298_257_223_563f64 / 1_000_000_000.0)
}

/// IEEE-754 `remainder(x, y)`: x - n*y with n the nearest integer to x/y,
/// ties to even.
fn remainder(x: f64, y: f64) -> f64 {
    let q = x / y;
    let mut n = q.round();
    // round() is ties-away-from-zero; fix up exact halves to ties-to-even.
    if (q - q.trunc()).abs() == 0.5 && n % 2.0 != 0.0 {
        n -= q.signum();
    }
    x - n * y
}

/// `Math::AngNormalize`.
fn ang_normalize(x: f64) -> f64 {
    let y = remainder(x, TD);
    if y.abs() == HD {
        HD.copysign(x)
    } else {
        y
    }
}

/// `Math::sum` (the exact two-sum).
fn two_sum(u: f64, v: f64) -> (f64, f64) {
    let s = u + v;
    let mut up = s - v;
    let mut vpp = s - up;
    up -= u;
    vpp -= v;
    let t = if s != 0.0 { -(up + vpp) } else { s };
    (s, t)
}

/// `Math::AngDiff`.
fn ang_diff(x: f64, y: f64) -> f64 {
    let (mut d, mut e) = two_sum(remainder(-x, TD), remainder(y, TD));
    let r = two_sum(remainder(d, TD), e);
    d = r.0;
    e = r.1;
    if d == 0.0 || d.abs() == HD {
        d = d.copysign(if e == 0.0 { y - x } else { -e });
    }
    d
}

/// `Math::LatFix`.
fn lat_fix(x: f64) -> f64 {
    if x.abs() > QD {
        f64::NAN
    } else {
        x
    }
}

/// `Math::sincosd`, which reduces the argument exactly before converting.
fn sincosd(x: f64) -> (f64, f64) {
    let q = x / QD;
    let mut n = q.round();
    if (q - q.trunc()).abs() == 0.5 && n % 2.0 != 0.0 {
        n -= q.signum();
    }
    let r = (x - n * QD) * DEGREE;
    let s = r.sin();
    let c = r.cos();
    let quadrant = (((n as i64) % 4) + 4) % 4;
    let (mut sinx, cosx) = match quadrant {
        0 => (s, c),
        1 => (c, -s),
        2 => (-s, -c),
        _ => (-c, s),
    };
    if sinx == 0.0 {
        sinx = sinx.copysign(x);
    }
    (sinx, cosx)
}

/// `Math::atan2d`.
fn atan2d(y: f64, x: f64) -> f64 {
    let (mut x, mut y) = (x, y);
    let mut q = 0;
    if y.abs() > x.abs() {
        std::mem::swap(&mut x, &mut y);
        q = 2;
    }
    if x.is_sign_negative() {
        x = -x;
        q += 1;
    }
    let ang = y.atan2(x) / DEGREE;
    match q {
        1 => HD.copysign(y) - ang,
        2 => QD - ang,
        3 => -QD + ang,
        _ => ang,
    }
}

fn atand(x: f64) -> f64 {
    atan2d(x, 1.0)
}

/// `Math::eatanhe`.
fn eatanhe(x: f64, es: f64) -> f64 {
    if es > 0.0 {
        es * (es * x).atanh()
    } else {
        -es * (es * x).atan()
    }
}

/// `Math::taupf`.
fn taupf(tau: f64, es: f64) -> f64 {
    if tau.is_finite() {
        let tau1 = 1.0f64.hypot(tau);
        let sig = eatanhe(tau / tau1, es).sinh();
        1.0f64.hypot(sig) * tau - sig * tau1
    } else {
        tau
    }
}

/// `Math::tauf` (Newton's method, at most 5 iterations).
fn tauf(taup: f64, es: f64) -> f64 {
    let tol = f64::EPSILON.sqrt() / 10.0;
    let taumax = 2.0 / f64::EPSILON.sqrt();
    let e2m = 1.0 - es * es;
    let mut tau = if taup.abs() > 70.0 {
        taup * eatanhe(1.0, es).exp()
    } else {
        taup / e2m
    };
    let stol = tol * 1.0f64.max(taup.abs());
    if !(tau.abs() < taumax) {
        return tau;
    }
    for _ in 0..5 {
        let taupa = taupf(tau, es);
        let dtau = (taup - taupa) * (1.0 + e2m * tau * tau)
            / (e2m * 1.0f64.hypot(tau) * 1.0f64.hypot(taupa));
        tau += dtau;
        if !(dtau.abs() >= stol) {
            break;
        }
    }
    tau
}

/// `Math::polyval`.
fn polyval(n: i32, p: &[f64], off: usize, x: f64) -> f64 {
    let mut i = 0usize;
    let mut y = if n < 0 { 0.0 } else { p[off + i] };
    let mut n = n;
    while n > 0 {
        n -= 1;
        i += 1;
        y = y * x + p[off + i];
    }
    y
}

// Coefficients generated by Maxima, copied verbatim from
// TransverseMercator.cpp for GEOGRAPHICLIB_TRANSVERSEMERCATOR_ORDER == 6.
const B1COEFF: [f64; 5] = [1.0, 4.0, 64.0, 256.0, 256.0];
const ALPCOEFF: [f64; 27] = [
    31564.0,
    -66675.0,
    34440.0,
    47250.0,
    -100800.0,
    75600.0,
    151200.0,
    -1983433.0,
    863232.0,
    748608.0,
    -1161216.0,
    524160.0,
    1935360.0,
    670412.0,
    406647.0,
    -533952.0,
    184464.0,
    725760.0,
    6601661.0,
    -7732800.0,
    2230245.0,
    7257600.0,
    -13675556.0,
    3438171.0,
    7983360.0,
    212378941.0,
    319334400.0,
];
const BETCOEFF: [f64; 27] = [
    384796.0,
    -382725.0,
    -6720.0,
    932400.0,
    -1612800.0,
    1209600.0,
    2419200.0,
    -1118711.0,
    1695744.0,
    -1174656.0,
    258048.0,
    80640.0,
    3870720.0,
    22276.0,
    -16929.0,
    -15984.0,
    12852.0,
    362880.0,
    -830251.0,
    -158400.0,
    197865.0,
    7257600.0,
    -435388.0,
    453717.0,
    15966720.0,
    20648693.0,
    638668800.0,
];

/// `GeographicLib::TransverseMercator` (the Krüger series, order 6).
#[derive(Clone, Debug)]
pub struct TransverseMercator {
    #[allow(dead_code)]
    a: f64,
    k0: f64,
    es: f64,
    e2m: f64,
    e2: f64,
    c: f64,
    a1: f64,
    b1: f64,
    alp: [f64; MAXPOW + 1],
    bet: [f64; MAXPOW + 1],
}

impl TransverseMercator {
    pub fn new(a: f64, f: f64, k0: f64) -> Self {
        let e2 = f * (2.0 - f);
        let es = (if f < 0.0 { -1.0 } else { 1.0 }) * e2.abs().sqrt();
        let e2m = 1.0 - e2;
        let c = e2m.sqrt() * eatanhe(1.0, es).exp();
        let n = f / (2.0 - f);

        let m = (MAXPOW / 2) as i32;
        let b1 = polyval(m, &B1COEFF, 0, n * n) / (B1COEFF[m as usize + 1] * (1.0 + n));
        let a1 = b1 * a;

        let mut alp = [0.0f64; MAXPOW + 1];
        let mut bet = [0.0f64; MAXPOW + 1];
        let mut o = 0usize;
        let mut d = n;
        for l in 1..=MAXPOW {
            let m = (MAXPOW - l) as i32;
            alp[l] = d * polyval(m, &ALPCOEFF, o, n) / ALPCOEFF[o + m as usize + 1];
            bet[l] = d * polyval(m, &BETCOEFF, o, n) / BETCOEFF[o + m as usize + 1];
            o += m as usize + 2;
            d *= n;
        }

        Self {
            a,
            k0,
            es,
            e2m,
            e2,
            c,
            a1,
            b1,
            alp,
            bet,
        }
    }

    /// `TransverseMercator::UTM()`.
    pub fn utm() -> Self {
        Self::new(WGS84_A, wgs84_f(), UTM_K0)
    }

    /// `TransverseMercator::Forward`. Returns (x, y, gamma, k).
    pub fn forward(&self, lon0: f64, lat: f64, lon: f64) -> (f64, f64, f64, f64) {
        let mut lat = lat_fix(lat);
        let mut lon = ang_diff(lon0, lon);
        let mut latsign = if lat.is_sign_negative() { -1.0 } else { 1.0 };
        let lonsign = if lon.is_sign_negative() { -1.0 } else { 1.0 };
        lon *= lonsign;
        lat *= latsign;
        let backside = lon > QD;
        if backside {
            if lat == 0.0 {
                latsign = -1.0;
            }
            lon = HD - lon;
        }
        let (sphi, cphi) = sincosd(lat);
        let (slam, clam) = sincosd(lon);

        let (xip, etap, mut gamma, mut k);
        if lat != QD {
            let tau = sphi / cphi;
            let taup = taupf(tau, self.es);
            xip = taup.atan2(clam);
            etap = (slam / taup.hypot(clam)).asinh();
            gamma = atan2d(slam * taup, clam * 1.0f64.hypot(taup));
            k = (self.e2m + self.e2 * cphi * cphi).sqrt() * 1.0f64.hypot(tau) / taup.hypot(clam);
        } else {
            xip = std::f64::consts::PI / 2.0;
            etap = 0.0;
            gamma = lon;
            k = self.c;
        }

        let c0 = (2.0 * xip).cos();
        let ch0 = (2.0 * etap).cosh();
        let s0 = (2.0 * xip).sin();
        let sh0 = (2.0 * etap).sinh();
        let mut a = Complex::new(2.0 * c0 * ch0, -2.0 * s0 * sh0);
        let mut n = MAXPOW;
        let mut y0 = if n & 1 == 1 {
            Complex::new(self.alp[n], 0.0)
        } else {
            Complex::zero()
        };
        let mut y1 = Complex::zero();
        let mut z0 = if n & 1 == 1 {
            Complex::new(2.0 * n as f64 * self.alp[n], 0.0)
        } else {
            Complex::zero()
        };
        let mut z1 = Complex::zero();
        if n & 1 == 1 {
            n -= 1;
        }
        while n != 0 {
            y1 = a.mul(&y0).sub(&y1).add_re(self.alp[n]);
            z1 = a.mul(&z0).sub(&z1).add_re(2.0 * n as f64 * self.alp[n]);
            n -= 1;
            y0 = a.mul(&y1).sub(&y0).add_re(self.alp[n]);
            z0 = a.mul(&z1).sub(&z0).add_re(2.0 * n as f64 * self.alp[n]);
            n -= 1;
        }
        a = a.scale(0.5);
        z1 = Complex::new(1.0, 0.0).sub(&z1).add(&a.mul(&z0));
        a = Complex::new(s0 * ch0, c0 * sh0);
        y1 = Complex::new(xip, etap).add(&a.mul(&y0));

        gamma -= atan2d(z1.im, z1.re);
        k *= self.b1 * z1.abs();
        let xi = y1.re;
        let eta = y1.im;
        let y = self.a1
            * self.k0
            * (if backside {
                std::f64::consts::PI - xi
            } else {
                xi
            })
            * latsign;
        let x = self.a1 * self.k0 * eta * lonsign;
        if backside {
            gamma = HD - gamma;
        }
        gamma *= latsign * lonsign;
        gamma = ang_normalize(gamma);
        k *= self.k0;
        (x, y, gamma, k)
    }

    /// `TransverseMercator::Reverse`. Returns (lat, lon, gamma, k).
    pub fn reverse(&self, lon0: f64, x: f64, y: f64) -> (f64, f64, f64, f64) {
        let mut xi = y / (self.a1 * self.k0);
        let mut eta = x / (self.a1 * self.k0);
        let xisign = if xi.is_sign_negative() { -1.0 } else { 1.0 };
        let etasign = if eta.is_sign_negative() { -1.0 } else { 1.0 };
        xi *= xisign;
        eta *= etasign;
        let backside = xi > std::f64::consts::PI / 2.0;
        if backside {
            xi = std::f64::consts::PI - xi;
        }
        let c0 = (2.0 * xi).cos();
        let ch0 = (2.0 * eta).cosh();
        let s0 = (2.0 * xi).sin();
        let sh0 = (2.0 * eta).sinh();
        let mut a = Complex::new(2.0 * c0 * ch0, -2.0 * s0 * sh0);
        let mut n = MAXPOW;
        let mut y0 = if n & 1 == 1 {
            Complex::new(-self.bet[n], 0.0)
        } else {
            Complex::zero()
        };
        let mut y1 = Complex::zero();
        let mut z0 = if n & 1 == 1 {
            Complex::new(-2.0 * n as f64 * self.bet[n], 0.0)
        } else {
            Complex::zero()
        };
        let mut z1 = Complex::zero();
        if n & 1 == 1 {
            n -= 1;
        }
        while n != 0 {
            y1 = a.mul(&y0).sub(&y1).add_re(-self.bet[n]);
            z1 = a.mul(&z0).sub(&z1).add_re(-2.0 * n as f64 * self.bet[n]);
            n -= 1;
            y0 = a.mul(&y1).sub(&y0).add_re(-self.bet[n]);
            z0 = a.mul(&z1).sub(&z0).add_re(-2.0 * n as f64 * self.bet[n]);
            n -= 1;
        }
        a = a.scale(0.5);
        z1 = Complex::new(1.0, 0.0).sub(&z1).add(&a.mul(&z0));
        a = Complex::new(s0 * ch0, c0 * sh0);
        y1 = Complex::new(xi, eta).add(&a.mul(&y0));

        let mut gamma = atan2d(z1.im, z1.re);
        let mut k = self.b1 / z1.abs();
        let xip = y1.re;
        let etap = y1.im;
        let s = etap.sinh();
        let c = 0.0f64.max(xip.cos());
        let r = s.hypot(c);
        let (mut lat, mut lon);
        if r != 0.0 {
            lon = atan2d(s, c);
            let sxip = xip.sin();
            let tau = tauf(sxip / r, self.es);
            gamma += atan2d(sxip * etap.tanh(), c);
            lat = atand(tau);
            k *= (self.e2m + self.e2 / (1.0 + tau * tau)).sqrt() * 1.0f64.hypot(tau) * r;
        } else {
            lat = QD;
            lon = 0.0;
            k *= self.c;
        }
        lat *= xisign;
        if backside {
            lon = HD - lon;
        }
        lon *= etasign;
        lon = ang_normalize(lon + lon0);
        if backside {
            gamma = HD - gamma;
        }
        gamma *= xisign * etasign;
        gamma = ang_normalize(gamma);
        k *= self.k0;
        (lat, lon, gamma, k)
    }
}

#[derive(Clone, Copy, Debug)]
struct Complex {
    re: f64,
    im: f64,
}

impl Complex {
    fn new(re: f64, im: f64) -> Self {
        Self { re, im }
    }
    fn zero() -> Self {
        Self::new(0.0, 0.0)
    }
    fn mul(&self, o: &Complex) -> Complex {
        Complex::new(
            self.re * o.re - self.im * o.im,
            self.re * o.im + self.im * o.re,
        )
    }
    fn add(&self, o: &Complex) -> Complex {
        Complex::new(self.re + o.re, self.im + o.im)
    }
    fn sub(&self, o: &Complex) -> Complex {
        Complex::new(self.re - o.re, self.im - o.im)
    }
    fn add_re(&self, v: f64) -> Complex {
        Complex::new(self.re + v, self.im)
    }
    fn scale(&self, s: f64) -> Complex {
        Complex::new(self.re * s, self.im * s)
    }
    fn abs(&self) -> f64 {
        self.re.hypot(self.im)
    }
}

/// `UTMUPS::StandardZone`'s special values.
pub const ZONE_UPS: i32 = 0;
pub const ZONE_STANDARD: i32 = -1;
pub const ZONE_INVALID: i32 = -4;

/// `MGRS::LatitudeBand`.
fn latitude_band(lat: f64) -> i32 {
    let ilat = lat.floor() as i32;
    (-10).max(9.min((ilat + 80) / 8 - 10))
}

/// `UTMUPS::CentralMeridian`.
pub fn central_meridian(zone: i32) -> f64 {
    (6 * zone - 183) as f64
}

/// `UTMUPS::StandardZone`.
pub fn standard_zone(lat: f64, lon: f64, setzone: i32) -> i32 {
    // MINZONE is 0 (== UPS), so any non-negative setzone is taken as given.
    if setzone >= 0 || setzone == ZONE_INVALID {
        return setzone;
    }
    if lat.is_nan() || lon.is_nan() {
        return ZONE_INVALID;
    }
    if setzone == -2 || (lat >= -80.0 && lat < 84.0) {
        let mut ilon = ang_normalize(lon).floor() as i32;
        if ilon == 180 {
            ilon = -180;
        }
        let mut zone = (ilon + 186) / 6;
        let band = latitude_band(lat);
        if band == 7 && zone == 31 && ilon >= 3 {
            zone = 32;
        } else if band == 9 && (0..42).contains(&ilon) {
            zone = 2 * ((ilon + 183) / 12) + 1;
        }
        zone
    } else {
        ZONE_UPS
    }
}

#[derive(Debug, PartialEq, Eq)]
pub enum UtmError {
    LatitudeOutOfRange,
    PolarRegionUnsupported,
    LongitudeTooFarFromZone,
    CoordinatesOutOfRange,
    BadZone,
}

/// Easting/northing offsets and limits for the UTM half of `UTMUPS`.
fn false_easting() -> f64 {
    5.0 * TILE
}

fn false_northing(northp: bool) -> f64 {
    if northp {
        0.0
    } else {
        100.0 * TILE
    }
}

fn check_coords(northp: bool, x: f64, y: f64) -> bool {
    let slop = TILE;
    let min_easting = 1.0 * TILE;
    let max_easting = 9.0 * TILE;
    let (min_northing, max_northing) = if northp {
        ((0 + 10 - 100) as f64 * TILE, 95.0 * TILE)
    } else {
        (10.0 * TILE, (100 + 95 - 0) as f64 * TILE)
    };
    !(x < min_easting - slop
        || x > max_easting + slop
        || y < min_northing - slop
        || y > max_northing + slop)
}

/// `UTMUPS::Forward` restricted to UTM. Returns (zone, northp, x, y, gamma, k).
pub fn utmups_forward(
    lat: f64,
    lon: f64,
    setzone: i32,
) -> Result<(i32, bool, f64, f64, f64, f64), UtmError> {
    if lat.abs() > QD {
        return Err(UtmError::LatitudeOutOfRange);
    }
    let northp = !lat.is_sign_negative();
    let zone = standard_zone(lat, lon, setzone);
    if zone == ZONE_INVALID {
        return Err(UtmError::BadZone);
    }
    if zone == ZONE_UPS {
        return Err(UtmError::PolarRegionUnsupported);
    }
    let lon0 = central_meridian(zone);
    let dlon = ang_diff(lon0, lon);
    if !(dlon <= 60.0) {
        return Err(UtmError::LongitudeTooFarFromZone);
    }
    let (mut x, mut y, gamma, k) = TransverseMercator::utm().forward(lon0, lat, lon);
    x += false_easting();
    y += false_northing(northp);
    if !check_coords(northp, x, y) {
        return Err(UtmError::CoordinatesOutOfRange);
    }
    Ok((zone, northp, x, y, gamma, k))
}

/// `UTMUPS::Reverse` restricted to UTM. Returns (lat, lon, gamma, k).
pub fn utmups_reverse(
    zone: i32,
    northp: bool,
    x: f64,
    y: f64,
) -> Result<(f64, f64, f64, f64), UtmError> {
    if !(1..=60).contains(&zone) {
        return Err(UtmError::BadZone);
    }
    let x = x - false_easting();
    let y = y - false_northing(northp);
    Ok(TransverseMercator::utm().reverse(central_meridian(zone), x, y))
}
