ARG ROS_DISTRO=jazzy

##############################################
# Gazebo Simulation Environment with VNC
##############################################
FROM tiryoh/ros2-desktop-vnc:${ROS_DISTRO}

RUN apt-get update && apt-get install -y \
    ros-${ROS_DISTRO}-turtlebot3* \
    ros-${ROS_DISTRO}-ros2-control \
    ros-${ROS_DISTRO}-ros2-controllers \
    ros-${ROS_DISTRO}-gz-ros2-control \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /home/fxrbindi/mower_ws/src

# COPY src/nav2_gps_waypoint_follower /home/fxrbindi/mower_ws/src/nav2_gps_waypoint_follower
# COPY src/lawer_qt_py /home/fxrbindi/mower_ws/src/lawer_qt_py

WORKDIR /home/fxrbindi/mower_ws

# Set shell to bash to use source
SHELL ["/bin/bash", "-c"]
RUN source /opt/ros/${ROS_DISTRO}/setup.bash && colcon build 

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc && \
    echo "source /home/fxrbindi/mower_ws/install/setup.bash" >> ~/.bashrc




CMD ["/bin/bash"]
