networks:
  rosnet:
    name: rosnet
    driver: bridge

services:
  lawan_node_dev:
    # name of this service, will be used in devcontainer.json
    image: lawan_node_dev # thw image will have this name once built
    extends:
      file: docker-compose.cv.yaml # extend the below service from this file
      service: lawan_node_cv
    build:
      context: .
      dockerfile: Dockerfile # the only dockerfile
      args:
        USER_NAME: $USER_NAME # will be taken from .env file, run export_env.sh first
        USER_ID: $USER_ID
        GROUP_NAME: $GROUP_NAME
        GROUP_ID: $GROUP_ID
      target: dev # must match the stage name in Dockerfile
    user: $USER_NAME # will login as your usename
    networks:
      - rosnet
    ipc: host
    pid: host
    # devices: 
    #   - /dev/imu_usb:/dev/imu_usb
    #   - /dev/stmcom:/dev/stmcom # Interactive shell
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/$USER_NAME/mower_ws # mount workspace directory inside the container

  # Gazebo Simulation Environment with VNC
  gazebo:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.gazebo
    networks:
      - rosnet
    ipc: host
    security_opt:
      - seccomp=unconfined
    working_dir: /home/$USER_NAME/mower_ws
    ports:
      - "6080:80" # noVNC web interface
    # volumes:
    #   - ../:/home/$USER_NAME/mower_ws/src/nav2_gps_waypoint_follower
    privileged: true # Gazebo 可能需要硬體加速
    shm_size: '2gb' # 增加共享記憶體以提升 Gazebo 效能
