ARG ROS_DISTRO=jazzy

FROM tiryoh/ros2-desktop-vnc:${ROS_DISTRO}

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y \
    python3-pyqt5 \
    python3-serial \
    ros-${ROS_DISTRO}-rviz2 \
    ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
    && rm -rf /var/lib/apt/lists/*

COPY .devcontainer/zenoh/rviz2.desktop /etc/xdg/autostart/rviz2.desktop
COPY .devcontainer/zenoh/lawer_qt.desktop /etc/xdg/autostart/lawer_qt.desktop
COPY .devcontainer/zenoh/lawer_qt.desktop /usr/share/applications/lawer_qt.desktop
COPY utiles/start-rviz-zenoh.sh /usr/local/bin/start-rviz-zenoh.sh
COPY utiles/start-mower-qt-zenoh.sh /usr/local/bin/start-mower-qt-zenoh.sh

RUN chmod +x /usr/local/bin/start-rviz-zenoh.sh /usr/local/bin/start-mower-qt-zenoh.sh
