ARG ROS_DISTRO=jazzy

FROM ros:${ROS_DISTRO}-ros-base AS gps_runtime_base

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y \
    ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
    ros-${ROS_DISTRO}-ublox-gps \
    && rm -rf /var/lib/apt/lists/*

FROM gps_runtime_base AS gps_runtime

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc

CMD ["bash"]
