services:
  lawan_node_dev:
    # name of this service, will be used in devcontainer.json
    image: lawan_node_dev # thw image will have this name once built
    extends:
      file: docker-compose.cv.yaml # extend the below service from this file
      service: lawan_node_cv
    build:
      context: .
      dockerfile: Dockerfile # the only dockerfile
      args:
        USER_NAME: $USER_NAME # will be taken from .env file, run export_env.sh first
        USER_ID: $USER_ID
        GROUP_NAME: $GROUP_NAME
        GROUP_ID: $GROUP_ID
      target: dev # must match the stage name in Dockerfile
    user: $USER_NAME # will login as your usename
    network_mode: host
    # Avoid privileged mode here: the serial symlink /dev/stmcom is more
    # stable when we keep it as an explicit device mapping.
    devices:
      - /dev/imu_usb:/dev/imu_usb
      - /dev/stmcom:/dev/stmcom # Interactive shell
    device_cgroup_rules:
      - 'c 13:* rmw'
    group_add:
      - "996"
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/$USER_NAME/mower_ws # mount workspace directory inside the container
      - /dev/input:/dev/input
      - /run/udev:/run/udev:ro
    working_dir: /home/$USER_NAME/mower_ws # set the working directory inside the container
    # command: source install/setup.bash && ros2 launch nav2_gps_waypoint_follower mower.launch.py # command to run when the container starts 
