<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mower_bringup</name>
  <version>0.0.0</version>
  <description>Mower bringup: launch files, Nav2, localization, simulation assets</description>
  <maintainer email="edwards940428@gmail.com">fxrbindi</maintainer>
  <license>Apache-2.0</license>

  <depend>nav2_bringup</depend>
  <exec_depend>joy</exec_depend>
  <exec_depend condition="$MOWER_BUILD_TARGET != 'sim'">mower_controller</exec_depend>
  <exec_depend>mower_description</exec_depend>
  <exec_depend>mower_teleop</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>twist_mux</exec_depend>
  <exec_depend>wit_ros2_imu</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>mower_mission</exec_depend>
  <exec_depend>nav_robot</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
